name: "Pull Request Labeler"

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        configuration-path: .github/labeler.yml
        sync-labels: true
